name: release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Setup ko
      uses: imjasonh/setup-ko
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release-multiarch-manifest:
    runs-on: ubuntu-latest
    needs: release-images
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build multi-arch manifest
      run: |
        set -euo pipefail
        tag="$(git describe --tag --always --dirty)"
        export KO_DOCKER_REPO="ghcr.io/${{ github.repository }}:${tag}"
        ko publish --platform=all .
