name: release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Setup ko
      run:  go install github.com/google/ko@latest
    - name: Setup crane
      run:  go install github.com/google/go-containerregistry/cmd/crane@latest
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push multi-arch container images
      run: |
        set -euo pipefail
        tag="$(git describe --tag --always --dirty)"
        export KO_DOCKER_REPO="ghcr.io/${{ github.repository }}"
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "${{ github.token }}" | ko login ghcr.io --username ignored --password-stdin
        set -x
        img="$(ko publish --platform=all .)"
        echo "Built image: $img"
        crane tag "$img" "$tag"
